### PR TITLE
Remove unused fields email, gmail

### PR DESCRIPTION
**Pull request by VadimDyachenko**
connect #60

### CODE REVIEW

**Review by asidun — APPROVED** [review]

**Comment by danilkuznetsov** [comment]
I think, that we should not remove these fields, because email is main key in many our legacy services. For example LMS or google docs.

**Review by adaleorion — CHANGES_REQUESTED** [review]
I think, that we should not remove these fields, because email is main key in many our legacy services. For example LMS or google docs.

**Comment by adaleorion** [comment]
@OlgaKulikova 
what do you think about my comment ?

**Comment by OlgaKulikova** [comment]
@danilkuznetsov We don't use these fields now for any endpoints. So we decided remove them now and if we need them further we will add again.

**Comment by adaleorion** [comment]
@OlgaKulikova 
ok, let's do it.

**Review by adaleorion — APPROVED** [review]

**Pull request merged**
