### PR TITLE
#86 add autoreconnect to MySQL

### PR DESCRIPTION
**Pull request by petrokramar**
Connect to #86

### CODE REVIEW

**Comment by adaleorion** [comment]
@starikivan 
Vadim found this article https://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect

It has some note about autoreconnect

what do you think about this?

**Comment by OlgaKulikova** [comment]
@danilkuznetsov do you think @starikivan 's approach is not working?

**Comment by VadimDyachenko** [comment]
I think, it can work well too, but it's on mysql jdbc driver layer. We will not write all the parameters in one line.
In the proposed article, the setting works at the spring datasource layer and does not depend on the type of the database.

**Comment by adaleorion** [comment]
@OlgaKulikova 
this approach works, but I found some note in link 
https://stackoverflow.com/questions/22684807/spring-boot-jpa-configuring-auto-reconnect

```
Note that the use of autoReconnect is not recommended:

The use of this feature is not recommended, because it has side effects related to session state and data consistency when applications don't handle SQLExceptions properly, and is only designed to be used when you are unable to configure your application to handle SQLExceptions resulting from dead and stale connections properly.
``` 
The author recommended using spring data options for solution problem. 

I wanted to get advice about it.

**Review by adaleorion — APPROVED** [review]

**Pull request merged**
